### GET ALL CUSTOMERS
GET http://localhost:8000/registrasi
Accept: application/json

### CREATE A CUSTOMER
POST http://localhost:8000/registrasi
Content-Type: application/json

{
  "email": "sam4@gmail.com",
  "password": "sam4",
  "nama": "sam4",
  "alamat": "tinggam4",
  "id_kelurahan": "pakansari"
}

### GET BY ID
GET http://localhost:8000/registrasi/6eb9ccda-eb54-474a-9c7c-28c61d9c5ad8
Accept: application/json

### DELETE BY ID
DELETE http://localhost:8000/registrasi/6eb9ccda-eb54-474a-9c7c-28c61d9c5ad8
Accept: application/json

### UPDATE BY ID
PUT http://localhost:8000/registrasi/7e54c66a-e029-4c69-a000-3cbe3bb4507e
Content-Type: application/json

{
  "email": "update@gmail.com",
  "password": "update",
  "nama": "update",
  "alamat": "update",
  "id_kelurahan": "cikeas"
}

###

GET http://localhost:8000/registrasi/kelurahan/pakansari
Accept: application/json